### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ofirkris** [OndrejTexler/Few-Shot-Patch-Based-Training#1]
Hi, thanks for sharing your amazing work.
I'm eager to test it, and don't have the computational resources to train it, can you kindly share the trained weights?

My email - ofirseo [@] gmail.com

**Comment by illeatmyhat** [comment]
Releasing a trained model for easy evaluation would be appreciated in general.

**Comment by OndrejTexler** [comment]
Hello. To train it you do not need any "extreme" computational resources (any consumer-grade Nvidia GPU not older than, let's say, years should be just fine). Anyway, I agree, that having training weights released would be nice for evaluation. I will prepare some .pth models and release them soon - thanks for the suggestion! :-)

**Comment by OndrejTexler** [comment]
I just released the pre-trained model and updated the README.md
