### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by lajiji** [OndrejTexler/Few-Shot-Patch-Based-Training#12]
Hi,I want to know how long does it take to train this model?

**Comment by OndrejTexler** [comment]
Hello @lajiji. It really depends on resolution and GPU, but let's say that for 512x512 on a decent GPU it takes between 2-10 minutes. On 400x400px on NVIDIA V100 it is possible to train quite decent model in about 20sec.

Anyway, check the paper: https://ondrejtexler.github.io/res/Texler20-SIG_patch-based_training_main.pdf
