### ISSUE TITLE
Is cuda required?

### ISSUE THREAD

**Issue by JonasLoos** [OndrejTexler/Few-Shot-Patch-Based-Training#3]
I tried to test this, but it seems `generate.py ... --device cpu` doesn't work due to missing fp16-support in pytorch ([see this](https://github.com/pytorch/pytorch/issues/23377#issuecomment-515833386), I don't have a nvidia gpu). If there is no way to run this without a nvidia gpu, I would suggest to add this requirement to the `README.md`.

**Comment by OndrejTexler** [comment]
Hello Jonas. Thanks for pointing this out. It seems that I have not tested my recent performance optimization on CPU, and I introduced this bug. I fixed it and pushed the changes. Please, pull the latest changes and try it again.

PyTorch does not support 16-bit floats on CPU; so now when you specify `--device "cpu"`, the model and input tensor are not casted to 16-bit floats, but remain 32-bit floats.

**Comment by JonasLoos** [comment]
it works - thanks!
