### ISSUE TITLE
how resume training?

### ISSUE THREAD

**Issue by molo32** [OndrejTexler/Few-Shot-Patch-Based-Training#6]
How can I continue the training?
when I quit python and then want to continue training it starts from scratch and overwrites the pths.
that is, it was in model_00011.pth and then I want to continue but it starts in model_00000.pth, I want it to continue from model_00011.pth.

**Comment by OndrejTexler** [comment]
Thanks for the question. The code is actually there, but it is neither documented in the readme nor exposed as an argument.

To load the saved generator, in train.py comment the line 79 and uncomment line 80 (and set the correct path to the .pth model for generator)
https://github.com/OndrejTexler/Few-Shot-Patch-Based-Training/blob/master/train.py#L80

You will also need to load the discriminator, in train.py comment line 85 and uncomment line 86
https://github.com/OndrejTexler/Few-Shot-Patch-Based-Training/blob/master/train.py#L86

But you need to have the discriminator .pth. To save the discriminator .pth during the training, uncomment line 156 in trainers.py
https://github.com/OndrejTexler/Few-Shot-Patch-Based-Training/blob/master/trainers.py#L156

I hope it helps!
