### ISSUE TITLE
how generate smooth result for video 

### ISSUE THREAD

**Issue by andorxornot** [OndrejTexler/Few-Shot-Patch-Based-Training#7]
hi, Ondrej!
i liked your work very much. i trained the model and generated the final result. but each final frame is very different from the previous one. so i can't generate a smooth video like with ebsynth. what should i do for this?

**Comment by OndrejTexler** [comment]
Hello @andorxornot, sorry for the late reply. I just updated the repo with the tools to deal with temporal instability. See my last answer to the issue: https://github.com/OndrejTexler/Few-Shot-Patch-Based-Training/issues/4, and the chapter **Temporal Consistency [Optional]** in the updated Readme.md

Although, I am not 100% sure what are you referring to by saying: "but each final frame is very different from the previous one". Do you mean temporal flickering or something else?

**Comment by andorxornot** [comment]
oh, yes, that's just what I needed! thank you so much.
